<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ClinicaMedica</RootNamespace>
    <AssemblyName>ClinicaMedica</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Negocio\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClinicaMedica.Datos\ClinicaMedica.Datos.csproj" />
    <ProjectReference Include="..\ClinicaMedica.Negocio\ClinicaMedica.Negocio.csproj" />
  </ItemGroup>

</Project>
