<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>ClinicaMedica.Negocio</RootNamespace>
    <AssemblyName>ClinicaMedica.Negocio</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClinicaMedica.Datos\ClinicaMedica.Datos.csproj" />
  </ItemGroup>

</Project>
